# Macro file for the initialization of example B1
# in interactive session
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 0
# verbose para classe evento(FICA MUIT LONGO)
#/event/verbose 1
#verbose para tracking (FICA MUITO LONGO)
#/tracking/verbose 1
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac
